/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TokenBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_RETRY_ATTEMPTS"
      | "REQUEST_TIMEOUT"
      | "antelope_bridge_evm_address"
      | "antelope_symbol"
      | "antelope_token_contract"
      | "antelope_token_name"
      | "bridge"
      | "bridgeTo"
      | "evm_approvedToken"
      | "evm_decimals"
      | "fee"
      | "max_requests_per_requestor"
      | "min_amount"
      | "owner"
      | "refundAttempts"
      | "refundSuccessful"
      | "refunds"
      | "removeRequest"
      | "renounceOwnership"
      | "requestAttempts"
      | "requestSuccessful"
      | "request_counts"
      | "requests"
      | "retryFailedRefunds"
      | "retryFailedRequests"
      | "setAntelopeBridgeEvmAddress"
      | "setFee"
      | "setMaxRequestsPerRequestor"
      | "setTokenInfo"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BridgeRequest"
      | "BridgeTransaction"
      | "OwnershipTransferred"
      | "RefundRetryStatus"
      | "RefundStatus"
      | "RequestRetryStatus"
      | "RequestStatusCallback"
      | "ValidationStatus"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_RETRY_ATTEMPTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REQUEST_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "antelope_bridge_evm_address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "antelope_symbol",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "antelope_token_contract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "antelope_token_name",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bridge",
    values: [AddressLike, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeTo",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "evm_approvedToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "evm_decimals",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "max_requests_per_requestor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "min_amount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refundAttempts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refundSuccessful",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestAttempts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestSuccessful",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "request_counts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "retryFailedRefunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "retryFailedRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAntelopeBridgeEvmAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxRequestsPerRequestor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenInfo",
    values: [AddressLike, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_RETRY_ATTEMPTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REQUEST_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "antelope_bridge_evm_address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "antelope_symbol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "antelope_token_contract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "antelope_token_name",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bridge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bridgeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "evm_approvedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evm_decimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "max_requests_per_requestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "min_amount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundAttempts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundSuccessful",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refunds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAttempts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestSuccessful",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "request_counts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "retryFailedRefunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retryFailedRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAntelopeBridgeEvmAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxRequestsPerRequestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BridgeRequestEvent {
  export type InputTuple = [
    id: BigNumberish,
    sender: AddressLike,
    token: AddressLike,
    antelope_token_contract: BytesLike,
    antelope_symbol: BytesLike,
    amount: BigNumberish,
    receiver: BytesLike,
    timestamp: BigNumberish,
    memo: BytesLike,
    status: BytesLike,
    reason: BytesLike
  ];
  export type OutputTuple = [
    id: bigint,
    sender: string,
    token: string,
    antelope_token_contract: string,
    antelope_symbol: string,
    amount: bigint,
    receiver: string,
    timestamp: bigint,
    memo: string,
    status: string,
    reason: string
  ];
  export interface OutputObject {
    id: bigint;
    sender: string;
    token: string;
    antelope_token_contract: string;
    antelope_symbol: string;
    amount: bigint;
    receiver: string;
    timestamp: bigint;
    memo: string;
    status: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeTransactionEvent {
  export type InputTuple = [
    receiver: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    status: BytesLike,
    timestamp: BigNumberish,
    sender: BytesLike,
    from_token_contract: BytesLike,
    from_token_symbol: BytesLike,
    reason: BytesLike
  ];
  export type OutputTuple = [
    receiver: string,
    token: string,
    amount: bigint,
    status: string,
    timestamp: bigint,
    sender: string,
    from_token_contract: string,
    from_token_symbol: string,
    reason: string
  ];
  export interface OutputObject {
    receiver: string;
    token: string;
    amount: bigint;
    status: string;
    timestamp: bigint;
    sender: string;
    from_token_contract: string;
    from_token_symbol: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundRetryStatusEvent {
  export type InputTuple = [
    id: BigNumberish,
    sender: AddressLike,
    antelope_token_contract: BytesLike,
    antelope_symbol: BytesLike,
    amount: BigNumberish,
    receiver: BytesLike,
    attemptCount: BigNumberish,
    status: BigNumberish,
    timestamp: BigNumberish,
    reason: BytesLike
  ];
  export type OutputTuple = [
    id: bigint,
    sender: string,
    antelope_token_contract: string,
    antelope_symbol: string,
    amount: bigint,
    receiver: string,
    attemptCount: bigint,
    status: bigint,
    timestamp: bigint,
    reason: string
  ];
  export interface OutputObject {
    id: bigint;
    sender: string;
    antelope_token_contract: string;
    antelope_symbol: string;
    amount: bigint;
    receiver: string;
    attemptCount: bigint;
    status: bigint;
    timestamp: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundStatusEvent {
  export type InputTuple = [
    id: BigNumberish,
    sender: AddressLike,
    antelope_token_contract: BytesLike,
    antelope_symbol: BytesLike,
    amount: BigNumberish,
    receiver: BytesLike,
    status: BigNumberish,
    timestamp: BigNumberish,
    reason: BytesLike
  ];
  export type OutputTuple = [
    id: bigint,
    sender: string,
    antelope_token_contract: string,
    antelope_symbol: string,
    amount: bigint,
    receiver: string,
    status: bigint,
    timestamp: bigint,
    reason: string
  ];
  export interface OutputObject {
    id: bigint;
    sender: string;
    antelope_token_contract: string;
    antelope_symbol: string;
    amount: bigint;
    receiver: string;
    status: bigint;
    timestamp: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestRetryStatusEvent {
  export type InputTuple = [
    id: BigNumberish,
    sender: AddressLike,
    antelope_token_contract: BytesLike,
    antelope_symbol: BytesLike,
    amount: BigNumberish,
    receiver: BytesLike,
    attemptCount: BigNumberish,
    status: BigNumberish,
    timestamp: BigNumberish,
    reason: BytesLike
  ];
  export type OutputTuple = [
    id: bigint,
    sender: string,
    antelope_token_contract: string,
    antelope_symbol: string,
    amount: bigint,
    receiver: string,
    attemptCount: bigint,
    status: bigint,
    timestamp: bigint,
    reason: string
  ];
  export interface OutputObject {
    id: bigint;
    sender: string;
    antelope_token_contract: string;
    antelope_symbol: string;
    amount: bigint;
    receiver: string;
    attemptCount: bigint;
    status: bigint;
    timestamp: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestStatusCallbackEvent {
  export type InputTuple = [
    id: BigNumberish,
    sender: AddressLike,
    antelope_token_contract: BytesLike,
    antelope_symbol: BytesLike,
    amount: BigNumberish,
    receiver: BytesLike,
    status: BigNumberish,
    timestamp: BigNumberish,
    reason: BytesLike
  ];
  export type OutputTuple = [
    id: bigint,
    sender: string,
    antelope_token_contract: string,
    antelope_symbol: string,
    amount: bigint,
    receiver: string,
    status: bigint,
    timestamp: bigint,
    reason: string
  ];
  export interface OutputObject {
    id: bigint;
    sender: string;
    antelope_token_contract: string;
    antelope_symbol: string;
    amount: bigint;
    receiver: string;
    status: bigint;
    timestamp: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidationStatusEvent {
  export type InputTuple = [
    message: BytesLike,
    token: AddressLike,
    receiver: AddressLike,
    amount: BigNumberish,
    sender: BytesLike,
    from_token_contract: BytesLike,
    from_token_symbol: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    message: string,
    token: string,
    receiver: string,
    amount: bigint,
    sender: string,
    from_token_contract: string,
    from_token_symbol: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    message: string;
    token: string;
    receiver: string;
    amount: bigint;
    sender: string;
    from_token_contract: string;
    from_token_symbol: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenBridge extends BaseContract {
  connect(runner?: ContractRunner | null): TokenBridge;
  waitForDeployment(): Promise<this>;

  interface: TokenBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_RETRY_ATTEMPTS: TypedContractMethod<[], [bigint], "view">;

  REQUEST_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  antelope_bridge_evm_address: TypedContractMethod<[], [string], "view">;

  antelope_symbol: TypedContractMethod<[], [string], "view">;

  antelope_token_contract: TypedContractMethod<[], [string], "view">;

  antelope_token_name: TypedContractMethod<[], [string], "view">;

  bridge: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, receiver: string, memo: string],
    [void],
    "payable"
  >;

  bridgeTo: TypedContractMethod<
    [
      token: AddressLike,
      receiver: AddressLike,
      amount: BigNumberish,
      sender: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  evm_approvedToken: TypedContractMethod<[], [string], "view">;

  evm_decimals: TypedContractMethod<[], [bigint], "view">;

  fee: TypedContractMethod<[], [bigint], "view">;

  max_requests_per_requestor: TypedContractMethod<[], [bigint], "view">;

  min_amount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  refundAttempts: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  refundSuccessful: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  refunds: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        amount: bigint;
        antelope_token_contract: string;
        antelope_symbol: string;
        receiver: string;
        sender: string;
        evm_decimals: bigint;
        status: bigint;
        lastAttempt: bigint;
      }
    ],
    "view"
  >;

  removeRequest: TypedContractMethod<
    [id: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestAttempts: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  requestSuccessful: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  request_counts: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  requests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        sender: string;
        amount: bigint;
        requested_at: bigint;
        antelope_token_contract: string;
        antelope_symbol: string;
        receiver: string;
        evm_decimals: bigint;
        status: bigint;
        lastAttempt: bigint;
        memo: string;
      }
    ],
    "view"
  >;

  retryFailedRefunds: TypedContractMethod<[], [void], "nonpayable">;

  retryFailedRequests: TypedContractMethod<[], [void], "nonpayable">;

  setAntelopeBridgeEvmAddress: TypedContractMethod<
    [_antelope_bridge_evm_address: AddressLike],
    [void],
    "nonpayable"
  >;

  setFee: TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;

  setMaxRequestsPerRequestor: TypedContractMethod<
    [_max_requests_per_requestor: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenInfo: TypedContractMethod<
    [
      _evm_approvedToken: AddressLike,
      _antelope_token_contract: string,
      _antelope_token_name: string,
      _antelope_symbol: string
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_RETRY_ATTEMPTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REQUEST_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "antelope_bridge_evm_address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "antelope_symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "antelope_token_contract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "antelope_token_name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bridge"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, receiver: string, memo: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "bridgeTo"
  ): TypedContractMethod<
    [
      token: AddressLike,
      receiver: AddressLike,
      amount: BigNumberish,
      sender: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "evm_approvedToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "evm_decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "max_requests_per_requestor"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "min_amount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundAttempts"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "refundSuccessful"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refunds"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        amount: bigint;
        antelope_token_contract: string;
        antelope_symbol: string;
        receiver: string;
        sender: string;
        evm_decimals: bigint;
        status: bigint;
        lastAttempt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeRequest"
  ): TypedContractMethod<[id: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestAttempts"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestSuccessful"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "request_counts"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        sender: string;
        amount: bigint;
        requested_at: bigint;
        antelope_token_contract: string;
        antelope_symbol: string;
        receiver: string;
        evm_decimals: bigint;
        status: bigint;
        lastAttempt: bigint;
        memo: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "retryFailedRefunds"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "retryFailedRequests"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAntelopeBridgeEvmAddress"
  ): TypedContractMethod<
    [_antelope_bridge_evm_address: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxRequestsPerRequestor"
  ): TypedContractMethod<
    [_max_requests_per_requestor: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenInfo"
  ): TypedContractMethod<
    [
      _evm_approvedToken: AddressLike,
      _antelope_token_contract: string,
      _antelope_token_name: string,
      _antelope_symbol: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BridgeRequest"
  ): TypedContractEvent<
    BridgeRequestEvent.InputTuple,
    BridgeRequestEvent.OutputTuple,
    BridgeRequestEvent.OutputObject
  >;
  getEvent(
    key: "BridgeTransaction"
  ): TypedContractEvent<
    BridgeTransactionEvent.InputTuple,
    BridgeTransactionEvent.OutputTuple,
    BridgeTransactionEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RefundRetryStatus"
  ): TypedContractEvent<
    RefundRetryStatusEvent.InputTuple,
    RefundRetryStatusEvent.OutputTuple,
    RefundRetryStatusEvent.OutputObject
  >;
  getEvent(
    key: "RefundStatus"
  ): TypedContractEvent<
    RefundStatusEvent.InputTuple,
    RefundStatusEvent.OutputTuple,
    RefundStatusEvent.OutputObject
  >;
  getEvent(
    key: "RequestRetryStatus"
  ): TypedContractEvent<
    RequestRetryStatusEvent.InputTuple,
    RequestRetryStatusEvent.OutputTuple,
    RequestRetryStatusEvent.OutputObject
  >;
  getEvent(
    key: "RequestStatusCallback"
  ): TypedContractEvent<
    RequestStatusCallbackEvent.InputTuple,
    RequestStatusCallbackEvent.OutputTuple,
    RequestStatusCallbackEvent.OutputObject
  >;
  getEvent(
    key: "ValidationStatus"
  ): TypedContractEvent<
    ValidationStatusEvent.InputTuple,
    ValidationStatusEvent.OutputTuple,
    ValidationStatusEvent.OutputObject
  >;

  filters: {
    "BridgeRequest(uint256,address,address,bytes32,bytes32,uint256,bytes32,uint256,bytes32,bytes32,bytes32)": TypedContractEvent<
      BridgeRequestEvent.InputTuple,
      BridgeRequestEvent.OutputTuple,
      BridgeRequestEvent.OutputObject
    >;
    BridgeRequest: TypedContractEvent<
      BridgeRequestEvent.InputTuple,
      BridgeRequestEvent.OutputTuple,
      BridgeRequestEvent.OutputObject
    >;

    "BridgeTransaction(address,address,uint256,bytes32,uint256,bytes32,bytes32,bytes32,bytes32)": TypedContractEvent<
      BridgeTransactionEvent.InputTuple,
      BridgeTransactionEvent.OutputTuple,
      BridgeTransactionEvent.OutputObject
    >;
    BridgeTransaction: TypedContractEvent<
      BridgeTransactionEvent.InputTuple,
      BridgeTransactionEvent.OutputTuple,
      BridgeTransactionEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RefundRetryStatus(uint256,address,bytes32,bytes32,uint256,bytes32,uint256,uint8,uint256,bytes32)": TypedContractEvent<
      RefundRetryStatusEvent.InputTuple,
      RefundRetryStatusEvent.OutputTuple,
      RefundRetryStatusEvent.OutputObject
    >;
    RefundRetryStatus: TypedContractEvent<
      RefundRetryStatusEvent.InputTuple,
      RefundRetryStatusEvent.OutputTuple,
      RefundRetryStatusEvent.OutputObject
    >;

    "RefundStatus(uint256,address,bytes32,bytes32,uint256,bytes32,uint8,uint256,bytes32)": TypedContractEvent<
      RefundStatusEvent.InputTuple,
      RefundStatusEvent.OutputTuple,
      RefundStatusEvent.OutputObject
    >;
    RefundStatus: TypedContractEvent<
      RefundStatusEvent.InputTuple,
      RefundStatusEvent.OutputTuple,
      RefundStatusEvent.OutputObject
    >;

    "RequestRetryStatus(uint256,address,bytes32,bytes32,uint256,bytes32,uint256,uint8,uint256,bytes32)": TypedContractEvent<
      RequestRetryStatusEvent.InputTuple,
      RequestRetryStatusEvent.OutputTuple,
      RequestRetryStatusEvent.OutputObject
    >;
    RequestRetryStatus: TypedContractEvent<
      RequestRetryStatusEvent.InputTuple,
      RequestRetryStatusEvent.OutputTuple,
      RequestRetryStatusEvent.OutputObject
    >;

    "RequestStatusCallback(uint256,address,bytes32,bytes32,uint256,bytes32,uint8,uint256,bytes32)": TypedContractEvent<
      RequestStatusCallbackEvent.InputTuple,
      RequestStatusCallbackEvent.OutputTuple,
      RequestStatusCallbackEvent.OutputObject
    >;
    RequestStatusCallback: TypedContractEvent<
      RequestStatusCallbackEvent.InputTuple,
      RequestStatusCallbackEvent.OutputTuple,
      RequestStatusCallbackEvent.OutputObject
    >;

    "ValidationStatus(bytes32,address,address,uint256,bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      ValidationStatusEvent.InputTuple,
      ValidationStatusEvent.OutputTuple,
      ValidationStatusEvent.OutputObject
    >;
    ValidationStatus: TypedContractEvent<
      ValidationStatusEvent.InputTuple,
      ValidationStatusEvent.OutputTuple,
      ValidationStatusEvent.OutputObject
    >;
  };
}
