/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TokenBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "antelope_bridge_evm_address"
      | "antelope_symbol"
      | "antelope_token_contract"
      | "antelope_token_name"
      | "bridge"
      | "bridgeTo"
      | "evm_approvedToken"
      | "evm_decimals"
      | "fee"
      | "max_requests_per_requestor"
      | "min_amount"
      | "owner"
      | "refundSuccessful"
      | "refunds"
      | "removeRequest"
      | "renounceOwnership"
      | "requestSuccessful"
      | "request_counts"
      | "requests"
      | "setAntelopeBridgeEvmAddress"
      | "setFee"
      | "setMaxRequestsPerRequestor"
      | "setTokenInfo"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BridgeFromAntelopeFailed"
      | "BridgeFromAntelopeRefunded"
      | "BridgeFromAntelopeSucceeded"
      | "BridgeToAntelopeRequested"
      | "BridgeToAntelopeSucceeded"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "antelope_bridge_evm_address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "antelope_symbol",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "antelope_token_contract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "antelope_token_name",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bridge",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeTo",
    values: [AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "evm_approvedToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "evm_decimals",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "max_requests_per_requestor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "min_amount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refundSuccessful",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestSuccessful",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "request_counts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAntelopeBridgeEvmAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxRequestsPerRequestor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenInfo",
    values: [AddressLike, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "antelope_bridge_evm_address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "antelope_symbol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "antelope_token_contract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "antelope_token_name",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bridge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bridgeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "evm_approvedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evm_decimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "max_requests_per_requestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "min_amount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundSuccessful",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refunds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestSuccessful",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "request_counts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAntelopeBridgeEvmAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxRequestsPerRequestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BridgeFromAntelopeFailedEvent {
  export type InputTuple = [
    recipient: AddressLike,
    evm_approvedToken: AddressLike,
    amount: BigNumberish,
    refund_account: string
  ];
  export type OutputTuple = [
    recipient: string,
    evm_approvedToken: string,
    amount: bigint,
    refund_account: string
  ];
  export interface OutputObject {
    recipient: string;
    evm_approvedToken: string;
    amount: bigint;
    refund_account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeFromAntelopeRefundedEvent {
  export type InputTuple = [refund_id: BigNumberish];
  export type OutputTuple = [refund_id: bigint];
  export interface OutputObject {
    refund_id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeFromAntelopeSucceededEvent {
  export type InputTuple = [
    recipient: AddressLike,
    evm_approvedToken: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    recipient: string,
    evm_approvedToken: string,
    amount: bigint
  ];
  export interface OutputObject {
    recipient: string;
    evm_approvedToken: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeToAntelopeRequestedEvent {
  export type InputTuple = [
    request_id: BigNumberish,
    sender: AddressLike,
    evm_approvedToken: AddressLike,
    antelope_token_name: string,
    amount: BigNumberish,
    recipient: string
  ];
  export type OutputTuple = [
    request_id: bigint,
    sender: string,
    evm_approvedToken: string,
    antelope_token_name: string,
    amount: bigint,
    recipient: string
  ];
  export interface OutputObject {
    request_id: bigint;
    sender: string;
    evm_approvedToken: string;
    antelope_token_name: string;
    amount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeToAntelopeSucceededEvent {
  export type InputTuple = [
    request_id: BigNumberish,
    sender: AddressLike,
    antelope_token_name: string,
    amount: BigNumberish,
    recipient: string
  ];
  export type OutputTuple = [
    request_id: bigint,
    sender: string,
    antelope_token_name: string,
    amount: bigint,
    recipient: string
  ];
  export interface OutputObject {
    request_id: bigint;
    sender: string;
    antelope_token_name: string;
    amount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenBridge extends BaseContract {
  connect(runner?: ContractRunner | null): TokenBridge;
  waitForDeployment(): Promise<this>;

  interface: TokenBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  antelope_bridge_evm_address: TypedContractMethod<[], [string], "view">;

  antelope_symbol: TypedContractMethod<[], [string], "view">;

  antelope_token_contract: TypedContractMethod<[], [string], "view">;

  antelope_token_name: TypedContractMethod<[], [string], "view">;

  bridge: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, receiver: string],
    [void],
    "payable"
  >;

  bridgeTo: TypedContractMethod<
    [
      token: AddressLike,
      receiver: AddressLike,
      amount: BigNumberish,
      sender: string
    ],
    [void],
    "nonpayable"
  >;

  evm_approvedToken: TypedContractMethod<[], [string], "view">;

  evm_decimals: TypedContractMethod<[], [bigint], "view">;

  fee: TypedContractMethod<[], [bigint], "view">;

  max_requests_per_requestor: TypedContractMethod<[], [bigint], "view">;

  min_amount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  refundSuccessful: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  refunds: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, string, bigint] & {
        id: bigint;
        amount: bigint;
        antelope_token_name: string;
        antelope_symbol: string;
        receiver: string;
        evm_decimals: bigint;
      }
    ],
    "view"
  >;

  removeRequest: TypedContractMethod<
    [id: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestSuccessful: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  request_counts: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  requests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string, string, string, bigint] & {
        id: bigint;
        sender: string;
        amount: bigint;
        requested_at: bigint;
        antelope_token_name: string;
        antelope_symbol: string;
        receiver: string;
        evm_decimals: bigint;
      }
    ],
    "view"
  >;

  setAntelopeBridgeEvmAddress: TypedContractMethod<
    [_antelope_bridge_evm_address: AddressLike],
    [void],
    "nonpayable"
  >;

  setFee: TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;

  setMaxRequestsPerRequestor: TypedContractMethod<
    [_max_requests_per_requestor: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenInfo: TypedContractMethod<
    [
      _evm_approvedToken: AddressLike,
      _antelope_token_contract: string,
      _antelope_token_name: string,
      _antelope_symbol: string
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "antelope_bridge_evm_address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "antelope_symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "antelope_token_contract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "antelope_token_name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bridge"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, receiver: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "bridgeTo"
  ): TypedContractMethod<
    [
      token: AddressLike,
      receiver: AddressLike,
      amount: BigNumberish,
      sender: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "evm_approvedToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "evm_decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "max_requests_per_requestor"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "min_amount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundSuccessful"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refunds"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, string, bigint] & {
        id: bigint;
        amount: bigint;
        antelope_token_name: string;
        antelope_symbol: string;
        receiver: string;
        evm_decimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeRequest"
  ): TypedContractMethod<[id: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestSuccessful"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "request_counts"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string, string, string, bigint] & {
        id: bigint;
        sender: string;
        amount: bigint;
        requested_at: bigint;
        antelope_token_name: string;
        antelope_symbol: string;
        receiver: string;
        evm_decimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAntelopeBridgeEvmAddress"
  ): TypedContractMethod<
    [_antelope_bridge_evm_address: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxRequestsPerRequestor"
  ): TypedContractMethod<
    [_max_requests_per_requestor: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenInfo"
  ): TypedContractMethod<
    [
      _evm_approvedToken: AddressLike,
      _antelope_token_contract: string,
      _antelope_token_name: string,
      _antelope_symbol: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BridgeFromAntelopeFailed"
  ): TypedContractEvent<
    BridgeFromAntelopeFailedEvent.InputTuple,
    BridgeFromAntelopeFailedEvent.OutputTuple,
    BridgeFromAntelopeFailedEvent.OutputObject
  >;
  getEvent(
    key: "BridgeFromAntelopeRefunded"
  ): TypedContractEvent<
    BridgeFromAntelopeRefundedEvent.InputTuple,
    BridgeFromAntelopeRefundedEvent.OutputTuple,
    BridgeFromAntelopeRefundedEvent.OutputObject
  >;
  getEvent(
    key: "BridgeFromAntelopeSucceeded"
  ): TypedContractEvent<
    BridgeFromAntelopeSucceededEvent.InputTuple,
    BridgeFromAntelopeSucceededEvent.OutputTuple,
    BridgeFromAntelopeSucceededEvent.OutputObject
  >;
  getEvent(
    key: "BridgeToAntelopeRequested"
  ): TypedContractEvent<
    BridgeToAntelopeRequestedEvent.InputTuple,
    BridgeToAntelopeRequestedEvent.OutputTuple,
    BridgeToAntelopeRequestedEvent.OutputObject
  >;
  getEvent(
    key: "BridgeToAntelopeSucceeded"
  ): TypedContractEvent<
    BridgeToAntelopeSucceededEvent.InputTuple,
    BridgeToAntelopeSucceededEvent.OutputTuple,
    BridgeToAntelopeSucceededEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BridgeFromAntelopeFailed(address,address,uint256,string)": TypedContractEvent<
      BridgeFromAntelopeFailedEvent.InputTuple,
      BridgeFromAntelopeFailedEvent.OutputTuple,
      BridgeFromAntelopeFailedEvent.OutputObject
    >;
    BridgeFromAntelopeFailed: TypedContractEvent<
      BridgeFromAntelopeFailedEvent.InputTuple,
      BridgeFromAntelopeFailedEvent.OutputTuple,
      BridgeFromAntelopeFailedEvent.OutputObject
    >;

    "BridgeFromAntelopeRefunded(uint256)": TypedContractEvent<
      BridgeFromAntelopeRefundedEvent.InputTuple,
      BridgeFromAntelopeRefundedEvent.OutputTuple,
      BridgeFromAntelopeRefundedEvent.OutputObject
    >;
    BridgeFromAntelopeRefunded: TypedContractEvent<
      BridgeFromAntelopeRefundedEvent.InputTuple,
      BridgeFromAntelopeRefundedEvent.OutputTuple,
      BridgeFromAntelopeRefundedEvent.OutputObject
    >;

    "BridgeFromAntelopeSucceeded(address,address,uint256)": TypedContractEvent<
      BridgeFromAntelopeSucceededEvent.InputTuple,
      BridgeFromAntelopeSucceededEvent.OutputTuple,
      BridgeFromAntelopeSucceededEvent.OutputObject
    >;
    BridgeFromAntelopeSucceeded: TypedContractEvent<
      BridgeFromAntelopeSucceededEvent.InputTuple,
      BridgeFromAntelopeSucceededEvent.OutputTuple,
      BridgeFromAntelopeSucceededEvent.OutputObject
    >;

    "BridgeToAntelopeRequested(uint256,address,address,string,uint256,string)": TypedContractEvent<
      BridgeToAntelopeRequestedEvent.InputTuple,
      BridgeToAntelopeRequestedEvent.OutputTuple,
      BridgeToAntelopeRequestedEvent.OutputObject
    >;
    BridgeToAntelopeRequested: TypedContractEvent<
      BridgeToAntelopeRequestedEvent.InputTuple,
      BridgeToAntelopeRequestedEvent.OutputTuple,
      BridgeToAntelopeRequestedEvent.OutputObject
    >;

    "BridgeToAntelopeSucceeded(uint256,address,string,uint256,string)": TypedContractEvent<
      BridgeToAntelopeSucceededEvent.InputTuple,
      BridgeToAntelopeSucceededEvent.OutputTuple,
      BridgeToAntelopeSucceededEvent.OutputObject
    >;
    BridgeToAntelopeSucceeded: TypedContractEvent<
      BridgeToAntelopeSucceededEvent.InputTuple,
      BridgeToAntelopeSucceededEvent.OutputTuple,
      BridgeToAntelopeSucceededEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
